### ISSUE TITLE
Not passing build

### ISSUE THREAD

**Issue by MojioMS** [andischerer/cordova-plugin-logtofile#8]
After adding the plugin to the project, the build process fails with

```
> Task :app:packageDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Entry name 'resources.arsc' collided

**Comment by stephwildcode** [comment]
Hello, 

I've got the same issue : build failed with cordova-android 10.1.1

`        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Octet 1 de la s▒quence UTF-8 ▒ 1 octets non valide.
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
        at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1743)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.arrangeCapacity(XMLEntityScanner.java:1614)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipString(XMLEntityScanner.java:1679)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$XMLDeclDriver.next(XMLDocumentScannerImpl.java:753)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
        at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:207)
        ... 242 more


> Task :app:compileDebugJavaWithJavac
Note: C:\developpementNMR\Gits\DEV\mrsdigitale\pxv03-cordova\platforms\android\app\src\main\java\org\apache\cordova\logtofile\LogToFile.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:packageDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:packageDebug'.
> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
   > Entry name 'AndroidManifest.xml' collided`


Can you help me please ?

Thanks in advance.

**Comment by stephwildcode** [comment]
Hello, 

I found a way to build this plugin with cordova-android 10.1.1.

I used the following configuration to build : 
-JAVA_HOME with JDK 11.0.3
-Node JS 12.16.1
-edit platforms/android/app/build.gradle with

android {
    packagingOptions {
        exclude 'AndroidManifest.xml'
        exclude 'resources.arsc'
    }
...
}

then the command "cordova build android" should be successful.
